add_newline = true

scan_timeout = 12

[username]
disabled = true

[character]
error_symbol = "[â–¶](bold red)"
success_symbol = "[â–¶](bold green)"

[package]
disabled = true

[cmd_duration]
format = "ğŸ•› [$duration](bold yellow)"
min_time = 500

[docker_context]
format = "via [ğŸ‹ $context](blue bold) "
